export const FORM_SUBMIT = 'FORM_SUBMIT'
export const FORM_UPDATE = 'FORM_UPDATE'
export const FORM_ERROR = 'FORM_ERROR'
export const FORM_LOADING = 'FORM_LOADING'
export const FORM_CLEAR = 'FORM_CLEAR'
export const FORM_SUCCESS = 'FORM_SUCCESS'
